import pigpio
import steppers


pi=pigpio.pi()

quad= steppers.Quad(0x27,pi)
quad2=steppers.Quad(0x20,pi)

b1,b2,b3,b4= quad.getSteppers()
rotation,inout,updown,filament = quad2.getSteppers()
SPEED=20
def defaultSpeed():
	b1.setSpeed(SPEED)
	b2.setSpeed(SPEED)
	b3.setSpeed(SPEED)
	b4.setSpeed(SPEED)
defaultSpeed()
rotation.setSpeed(10)
inout.setSpeed(60)
updown.setSpeed(100)
filament.setSpeed(60)
#filament.rotate(-1)
#r.rotate(-1)
def f(dist):
	b3.rotate(-dist)
	b1.rotate(dist)

def b(dist):
	b3.rotate(dist)
	b1.rotate(-dist)
def r(dist):
	b2.rotate(-dist)
	b4.rotate(dist)
def l(dist):
	b2.rotate(dist)
	b4.rotate(-dist)
def br(dist):
	b1.rotate(-dist)
	b2.rotate(-dist)
	b3.rotate(dist)
	b4.rotate(dist)
def fl(dist):
	b1.rotate(dist)
	b2.rotate(dist)
	b3.rotate(-dist)
	b4.rotate(-dist)
def fr(dist):
	b1.rotate(dist)
	b2.rotate(-dist)
	b3.rotate(-dist)
	b4.rotate(dist)
def bl(dist):
	b1.rotate(-dist)
	b2.rotate(dist)
	b3.rotate(dist)
	b4.rotate(-dist)
def rotate(dist):
	b1.rotate(dist)
	b2.rotate(dist)
	b3.rotate(dist)
	b4.rotate(dist)
def rotate2(dist):
	b1.rotate(dist)
	b3.rotate(dist)
def barrier():
	quad.barrier()
	quad2.barrier()
def demo():
	f(1.5)
	barrier()
	rotate(.5)
	rotate(-1)
	rotate(.5)
	barrier()
	quad.off()
	rotation.rotate(.2)
	rotation.rotate(-.4)
	rotation.rotate(.2)
	barrier()
	quad2.off()
	b1.setSpeed(10)
	b2.setSpeed(10)
	b3.setSpeed(10)
	b4.setSpeed(10)
	fl(.5)
	bl(.5)
	br(.5)
	fr(.5)
	barrier()
	quad.off()
	defaultSpeed()
	updown.rotate(-5)
	updown.rotate(4)
	quad2.off()
	barrier()
	b1.setSpeed(10)
	b2.setSpeed(10)
	b3.setSpeed(10)
	b4.setSpeed(10)
	l(.5)
	r(1)
	l(.5)
	barrier()
	quad.off()
	inout.rotate(1)
	inout.rotate(-2)
	inout.rotate(1)
	barrier()
	defaultSpeed()
	filament.rotate(-5)
	filament.rotate(5)
	barrier()
	quad2.off()
	b(1.5)
	barrier()
	quad.off()
	inout.rotate(1)
	inout.rotate(-2)
	inout.rotate(1)
	inout.rotate(-.5)
	inout.rotate(.5)
	inout.rotate(-.5)
	inout.rotate(.5)
	updown.rotate(-5)
	updown.rotate(5)
	barrier()
	quad2.off()
	
	filament.rotate(-5)
	filament.rotate(5)
	rotation.rotate(.2)
	rotation.rotate(-.4)
	rotation.rotate(.2)
	rotation.rotate(.2)
	rotation.rotate(-.4)
	rotation.rotate(.2)
	barrier()

demo()


#quad.barrier()
#b1.rotate(1.75)
#b2.rotate(1.75)
#b3.rotate(1.75)
#b4.rotate(1.75)

#quad.barrier()
#b1.rotate(3)
#b2.rotate(-3)
#b3.rotate(-3)
#b4.rotate(3)

quad.barrier()
quad2.barrier()
quad.close()
quad2.close()

